export const religionOptions = [
    "Catholic",
    "Roman Catholic",
    "Iglesia ni Cristo",
    "Philippine Independent Church (Aglipayan)",
    "Baptist",
    "Methodist",
    "Pentecostal",
    "Presbyterian",
    "Anglican/Episcopalian",
    "Evangelical/Charismatic",
    "Seventh-day Adventist",
    "Jehovah's Witnesses",
    "The Church of Jesus Christ of Latter-day Saints (Mormon)",
    "Islam (Sunni)",
    "Islam (Shia)",
    "Buddhism",
    "Hinduism",
    "Indigenous/Animist",

];
