const ExcelJS = require('exceljs')
const fs = require('fs')

export async function generate_records() {
    const workbook = new ExcelJS.Workbook()

    // Create a sheet for each month
    const monthNames = [
        'January',
        'February',
        'March',
        'April',
        'May',
        'June',
        'July',
        'August',
        'September',
        'October',
        'November',
        'December',
    ]
    const worksheets = {} // Store references to worksheets
    for (const monthName of monthNames) {
        worksheets[monthName] = workbook.addWorksheet(monthName)
    }
    workbook.addWorksheet('Overall Report')
    // Load date data (replace with your data source)
    const dateData = [
        { date: '05/16/2001', type: 'Birth' },
        { date: '12/25/2023', type: 'Marriage' },
        { date: '02/14/2024', type: 'Death' },
        { date: '05/01/2001', type: 'Birth' },
    ]

    // Add data to respective sheets
    for (const entry of dateData) {
        const date = new Date(entry.date)
        const monthName = monthNames[date.getMonth()]
        const sheet = worksheets[monthName]

        sheet.addRow([entry.date, entry.type])
    }

    // Set workbook properties (optional)
    workbook.creator = 'Generated by VBCRAS'
    workbook.modified = new Date()
    workbook.views = [
        {
            x: 0,
            y: 0,
            width: 10000,
            height: 20000,
            firstSheet: 0,
            activeTab: 12,
            visibility: 'visible',
        },
    ]

    await workbook.xlsx.writeFile('records_by_month.xlsx')
    console.log('Excel file with monthly sheets created!')
}
