"""Fix Forms

Revision ID: c4ffe1d2aa15
Revises: 
Create Date: 2024-07-15 10:58:10.646084

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4ffe1d2aa15'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('birth_available', schema=None) as batch_op:
        batch_op.add_column(sa.Column('remarks', sa.String(), nullable=False))
        batch_op.alter_column('form_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'forms', ['form_id'], ['id'])

    with op.batch_alter_table('death_available', schema=None) as batch_op:
        batch_op.alter_column('form_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'forms', ['form_id'], ['id'])

    with op.batch_alter_table('marriage_available', schema=None) as batch_op:
        batch_op.alter_column('form_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=False)
        batch_op.create_foreign_key(None, 'forms', ['form_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marriage_available', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('form_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('death_available', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('form_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)

    with op.batch_alter_table('birth_available', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('form_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
        batch_op.drop_column('remarks')

    # ### end Alembic commands ###
